import { Product } from "@/data/catalog";

export const CATEGORY_OPTIONS = [{ value: "all", label: "All pieces" }, { value: "70s", label: "The 70s Study" }, { value: "90s", label: "The 90s Study" }, { value: "matchday", label: "Objects for Matchday" }] as const;
export const PRICE_OPTIONS = [{ value: "all", label: "All prices" }, { value: "under-1m", label: "Under Rp1m" }, { value: "1m-2.5m", label: "Rp1m — Rp2.5m" }, { value: "2.5m-plus", label: "Rp2.5m+" }] as const;
export const SORT_OPTIONS = [{ value: "featured", label: "Featured" }, { value: "newest", label: "Newest" }, { value: "price-asc", label: "Price: low to high" }, { value: "price-desc", label: "Price: high to low" }] as const;
export type CategoryFilter = (typeof CATEGORY_OPTIONS)[number]["value"];
export type PriceFilter = (typeof PRICE_OPTIONS)[number]["value"];
export type SortOption = (typeof SORT_OPTIONS)[number]["value"];
export type CatalogPreferences = { query: string; category: CategoryFilter; price: PriceFilter; sort: SortOption };
export const defaultCatalogPreferences: CatalogPreferences = { query: "", category: "all", price: "all", sort: "featured" };
const categories: Record<CategoryFilter, string | null> = { all: null, "70s": "The 70s Study", "90s": "The 90s Study", matchday: "Objects for Matchday" };
const validCategory = new Set<CategoryFilter>(CATEGORY_OPTIONS.map(option => option.value)); const validPrice = new Set<PriceFilter>(PRICE_OPTIONS.map(option => option.value)); const validSort = new Set<SortOption>(SORT_OPTIONS.map(option => option.value));
export function readCatalogPreferences(search: string): CatalogPreferences { const params = new URLSearchParams(search); const category = params.get("category"); const price = params.get("price"); const sort = params.get("sort"); return { query: (params.get("q") || "").slice(0, 80), category: validCategory.has(category as CategoryFilter) ? category as CategoryFilter : "all", price: validPrice.has(price as PriceFilter) ? price as PriceFilter : "all", sort: validSort.has(sort as SortOption) ? sort as SortOption : "featured" }; }
export function writeCatalogPreferences(preferences: CatalogPreferences) { const params = new URLSearchParams(); if (preferences.query.trim()) params.set("q", preferences.query.trim()); if (preferences.category !== "all") params.set("category", preferences.category); if (preferences.price !== "all") params.set("price", preferences.price); if (preferences.sort !== "featured") params.set("sort", preferences.sort); const search = params.toString(); return search ? `?${search}` : ""; }
export function applyCatalogPreferences(products: Product[], preferences: CatalogPreferences) { const normalizedQuery = preferences.query.trim().toLowerCase(); const filtered = products.filter(product => { const searchable = [product.name, product.collection, product.material, product.fit, product.story, ...product.details, ...product.colors].join(" ").toLowerCase(); const matchesQuery = !normalizedQuery || searchable.includes(normalizedQuery); const matchesCategory = !categories[preferences.category] || product.collection === categories[preferences.category]; const matchesPrice = preferences.price === "all" || (preferences.price === "under-1m" && product.price < 1000000) || (preferences.price === "1m-2.5m" && product.price >= 1000000 && product.price <= 2500000) || (preferences.price === "2.5m-plus" && product.price >= 2500000); return matchesQuery && matchesCategory && matchesPrice; }); if (preferences.sort === "price-asc") return [...filtered].sort((a, b) => a.price - b.price); if (preferences.sort === "price-desc") return [...filtered].sort((a, b) => b.price - a.price); if (preferences.sort === "newest") return [...filtered].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt)); return filtered; }
