/** @vitest-environment happy-dom */
import React from "react";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ useList: vi.fn(), useExport: vi.fn(), useUpdate: vi.fn(), mutate: vi.fn(), invalidate: vi.fn(), refetchExport: vi.fn() }));
vi.mock("@/_core/hooks/useAuth", () => ({ useAuth: () => ({ user: { role: "admin" }, loading: false, isAuthenticated: true }) }));
vi.mock("@/lib/trpc", () => ({ trpc: { adminOrders: { list: { useQuery: mocks.useList }, exportRows: { useQuery: mocks.useExport }, updateStatus: { useMutation: mocks.useUpdate } }, auth: { logout: { useMutation: () => ({ mutate: vi.fn() }) } }, analytics: { getStats: { useQuery: () => ({ data: { totalAddToBag: 10, todayAddToBag: 3, topProducts: [] } }) } }, useUtils: () => ({ adminOrders: { list: { invalidate: mocks.invalidate } }, auth: { me: { invalidate: vi.fn() } } }) } }));
vi.mock("@/const", () => ({ startLogin: vi.fn() }));
vi.mock("wouter", () => ({ Link: ({ children, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) => <a {...props}>{children}</a>, useLocation: () => ["/admin/orders", vi.fn()] }));
vi.mock("sonner", () => ({ toast: { success: vi.fn(), error: vi.fn() } }));
const exportMocks = vi.hoisted(() => ({ downloadOrderReport: vi.fn(), downloadOrderCsv: vi.fn() }));
vi.mock("@/lib/adminExport", () => ({ downloadOrderReport: exportMocks.downloadOrderReport, downloadOrderCsv: exportMocks.downloadOrderCsv }));
import AdminOrders from "../AdminOrders";

const orders = [{ id: 1, reference: "TR-READY123", customerName: "Nadia Pratama", email: "nadia@example.com", phone: "+628123456789", notes: "Please contact after 5pm.", items: '[{"productId":"junction-ls","name":"Junction Long Sleeve","quantity":1,"color":"Ink","size":"M","unitAmount":1888000,"lineTotal":1888000}]', subtotal: 1888000, currency: "IDR", status: "new", createdAt: new Date("2026-08-26") }, { id: 2, reference: "TR-CLOSED456", customerName: "Raka", email: "raka@example.com", phone: "+62811111111", notes: null, items: "[]", subtotal: 928000, currency: "IDR", status: "closed", createdAt: new Date("2026-08-25") }];
describe("admin order dashboard", () => {
  beforeEach(() => { mocks.mutate.mockReset(); mocks.refetchExport.mockResolvedValue({ data: orders }); mocks.useList.mockReturnValue({ data: { orders, total: 12, page: 1, pageSize: 10, totalPages: 2, summary: { new: { count: 9, amount: 3000000, change: 20 }, contacted: { count: 2, amount: 1500000, change: -33 }, closed: { count: 1, amount: 928000, change: 0 }, comparisonLabel: "previous 30 days" }, trend: [{ day: "2026-08-25", total: 2 }, { day: "2026-08-26", total: 2 }], overdueCount: 3, topProducts: [{ productId: "junction-ls", name: "Junction Long Sleeve", requestedQuantity: 5, requestCount: 3 }] }, isLoading: false, isError: false }); mocks.useExport.mockReturnValue({ refetch: mocks.refetchExport, isFetching: false }); mocks.useUpdate.mockReturnValue({ mutate: mocks.mutate, isPending: false }); });
  afterEach(cleanup);
  it("filters requests, reveals detail data, and updates a status", () => { render(<AdminOrders />); expect(screen.getByText("TR-READY123")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "View TR-READY123" })); expect(screen.getByText("Please contact after 5pm.")).toBeTruthy(); expect(screen.getAllByText("Junction Long Sleeve").length).toBeGreaterThan(0); fireEvent.change(screen.getByLabelText("Request status"), { target: { value: "contacted" } }); expect(mocks.mutate).toHaveBeenCalledWith(expect.objectContaining({ id: 1, status: "contacted" })); fireEvent.click(screen.getByRole("button", { name: /^New$/ })); expect(mocks.useList).toHaveBeenLastCalledWith(expect.objectContaining({ status: "new", search: undefined, productId: undefined, page: 1, pageSize: 10 }), expect.objectContaining({ enabled: true })); });
  it("shows a distinct error state instead of an empty request list", () => { mocks.useList.mockReturnValue({ data: undefined, isLoading: false, isError: true }); render(<AdminOrders />); expect(screen.getByText("Requests could not be loaded.")).toBeTruthy(); });
  it("searches, filters by date, moves to the next page, and exports compatible reports", async () => { render(<AdminOrders />); fireEvent.change(screen.getByPlaceholderText("Search customer name or request number"), { target: { value: "Nadia" } }); fireEvent.change(screen.getByLabelText("Start date"), { target: { value: "2026-08-01" } }); await waitFor(() => expect(mocks.useList).toHaveBeenLastCalledWith(expect.objectContaining({ status: undefined, search: "Nadia", productId: undefined, startDate: "2026-08-01", endDate: expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/), page: 1, pageSize: 10 }), expect.objectContaining({ enabled: true }))); fireEvent.click(screen.getByRole("button", { name: "Next" })); expect(mocks.useList).toHaveBeenLastCalledWith(expect.objectContaining({ status: undefined, search: "Nadia", productId: undefined, startDate: "2026-08-01", page: 2, pageSize: 10 }), expect.objectContaining({ enabled: true })); fireEvent.click(screen.getByRole("button", { name: /Export XLSX/i })); await waitFor(() => expect(mocks.refetchExport).toHaveBeenCalled()); await waitFor(() => expect(exportMocks.downloadOrderReport).toHaveBeenCalledWith(orders)); fireEvent.click(screen.getByRole("button", { name: /Export CSV/i })); await waitFor(() => expect(exportMocks.downloadOrderCsv).toHaveBeenCalledWith(orders)); });
  it("shows monitoring totals, the daily trend, and applies quick date presets", async () => { render(<AdminOrders />); expect(screen.getByText("Daily submissions")).toBeTruthy(); expect(screen.getByText("4 submissions")).toBeTruthy(); expect(screen.getByText((content) => content.includes("3.000.000") && content.includes("requested value"))).toBeTruthy(); expect(screen.getByText(/\+20% vs previous 30 days/i)).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Last 7 days" })); await waitFor(() => expect(mocks.useList.mock.lastCall?.[0]).toMatchObject({ startDate: expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/), endDate: expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/), page: 1 })); fireEvent.click(screen.getByRole("button", { name: "This month" })); await waitFor(() => expect(mocks.useList.mock.lastCall?.[0]?.startDate).toMatch(/^\d{4}-\d{2}-01$/)); });
  it("filters by product type and applies inline New-status actions", async () => { render(<AdminOrders />); fireEvent.change(screen.getByLabelText("Product type"), { target: { value: "junction-ls" } }); await waitFor(() => expect(mocks.useList.mock.lastCall?.[0]).toMatchObject({ productId: "junction-ls", page: 1 })); fireEvent.click(screen.getByRole("button", { name: "Mark TR-READY123 as Contacted" })); expect(mocks.mutate).toHaveBeenCalledWith({ id: 1, status: "contacted" }); fireEvent.click(screen.getByRole("button", { name: "Mark TR-READY123 as Closed" })); expect(mocks.mutate).toHaveBeenCalledWith({ id: 1, status: "closed" }); });
  it("shows ranked requested pieces and focuses the list on overdue New requests", async () => { render(<AdminOrders />); expect(screen.getByText("Top requested pieces")).toBeTruthy(); expect(screen.getByText("5×")).toBeTruthy(); expect(screen.getByText("New requests waiting 24h+")).toBeTruthy(); fireEvent.click(screen.getAllByRole("button", { name: /Needs follow-up/i })[0]); await waitFor(() => expect(mocks.useList.mock.lastCall?.[0]).toMatchObject({ status: "new", overdueOnly: true, page: 1 })); });
});
